apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-platform-dashboard
  labels:
    app: data-platform-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-platform-dashboard
  template:
    metadata:
      labels:
        app: data-platform-dashboard
    spec:
      containers:
        - name: dashboard
          image: ghcr.io/ivan-hita/data-platform-observability:latest
          ports:
            - name: http
              containerPort: 8501
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: http
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
